---
services:
  restic-backup:
    image: ${SEAFILE_RESTIC_BACKUP_IMAGE:-seatable/restic-backup:1.5.3}
    container_name: restic-backup
    restart: unless-stopped
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/seafile-compose:/data/seafile-compose:ro
      - /opt/seafile-server/seafile:/data/seafile-server/seafile:ro
      - /opt/restic/local:/local
      - /opt/restic/restore:/restore
      - /opt/restic/cache:/root/.cache/restic
      - /opt/restic/logs:/var/log/restic
    environment:
      - TZ=${TIME_ZONE}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
      - RESTIC_DATA_SUBSET=${RESTIC_DATA_SUBSET:-1G}
      - RESTIC_FORGET_ARGS=${RESTIC_FORGET_ARGS:- --prune --keep-daily 6 --keep-weekly 4 --keep-monthly 6}
      - DATABASE_DUMP=${DATABASE_DUMP:-true}
      - DATABASE_HOST=${DATABASE_HOST:-mariadb}
      - DATABASE_USER=${DATABASE_USER:-root}
      - DATABASE_PASSWORD=${SEAFILE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - DATABASE_LIST=${DATABASE_LIST}
      - DATABASE_DUMP_COMPRESSION=${DATABASE_DUMP_COMPRESSION:-false}
      - LOG_TYPE=${LOG_TYPE:-stdout}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
