---
services:
  restic-backup:
    image: ${SEAFILE_RESTIC_BACKUP_IMAGE:-seatable/restic-backup:1.2.8}
    container_name: restic-backup
    restart: unless-stopped
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/seafile-compose:/data/seafile-compose:ro
      - /opt/seafile-server/seafile:/data/seafile-server/seafile:ro
      - /opt/restic/local:/local
      - /opt/restic/restore:/restore
      - /opt/restic/cache:/root/.cache/restic
      - /opt/restic/logs:/var/log/
    environment:
      - TZ=${TIME_ZONE}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
      - SEAFILE_DATABASE_DUMP=true
      - SEAFILE_DATABASE_PASSWORD=${SEAFILE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - LOG_TYPE=${LOG_TYPE:-stdout}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
