services:
  sdoc-server:
    image: seafileltd/sdoc-server:0.8.0
    restart: unless-stopped
    container_name: sdoc-server
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWD=${SEAFILE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - DB_NAME=sdoc_db
      - TIME_ZONE=${TIME_ZONE}
      - SDOC_SERVER_LETSENCRYPT=false
      - SDOC_SERVER_HOSTNAME=https://${SEAFILE_SERVER_HOSTNAME}/sdoc-server
      - SEAHUB_SERVICE_URL=https://${SEAFILE_SERVER_HOSTNAME}
    volumes:
      - /opt/seadoc-data:/shared
    depends_on:
      - mariadb
    networks:
      - backend-seafile-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7070/ping || exit 1"]
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s
