# Promtail configuration to enable logging based on container labels
# Taken from https://github.com/ruanbekker/docker-promtail-loki/blob/20d3f866528c2b7576a177851facf5ddafedf3de/config/promtail.yaml

# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # You will need to adjust this depending on your setup
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # The interesting bit starts here:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
      - cri: {}
      - multiline:
          # Logs should start with date, "T" is optional separator
          firstline: ^\d{4}-\d{2}-\d{2}[T ]\d{1,2}:\d{2}:\d{2}
          max_wait_time: 3s
